In [ ]:
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer

In [ ]:
model_name = "gpt2"  # Bạn có thể thay thế bằng một mô hình ngôn ngữ mã nguồn mở khác
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

generator = pipeline("text-generation", model=model, tokenizer=tokenizer)
label = 'based on'
prompt = f"Describe the label '{label}' in a simple and detailed way: "
descriptions = generator(prompt, max_length=50, num_return_sequences=1)

173

In [ ]:
descriptions[0]['generated_text'].replace(prompt, '').strip()

In [18]:
import numpy as np

def compute_new_logits(logits, group_size=3):
    # Đảm bảo logits là mảng numpy
    logits = np.array(logits)
    
    # Kiểm tra số phần tử có chia hết cho group_size
    if len(logits) % group_size != 0:
        raise ValueError("Length of logits must be divisible by group_size")
    
    print(logits.shape)
    # Reshape mảng logits để chia thành các nhóm group_size
    reshaped_logits = logits.reshape(-1, group_size, 3)
    print(reshaped_logits)
    
    # Tính trung bình của từng nhóm
    mean_logits = reshaped_logits.mean(axis=1)
    
    # Mở rộng lại thành mảng có cùng số chiều ban đầu
    reshaped_logits = mean_logits.reshape(-1, 3)
    
    return reshaped_logits

# Ví dụ
logits = [[0,1,2],[0,1,2],[0,1,2],[0,1,2],[0,1,2],[0,1,2]]
new_logits = compute_new_logits(logits)
print("New logits:", new_logits)


(6, 3)
[[[0 1 2]
  [0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
New logits: [[0. 1. 2.]
 [0. 1. 2.]]
